# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK.' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK.

  target 'VK.Tests' do
    pod 'Kingfisher', '~> 6.0.1'
    inherit! :search_paths
    # Pods for testing
  end
  pod 'RealmSwift'

  target 'VK.UITests' do
    # Pods for testing
  end

end
